# Generated by Django 3.2.9 on 2021-12-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_kosz_quantity'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
