# Generated by Django 3.2.9 on 2021-12-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211207_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='Ilość',
        ),
    ]
