# Generated by Django 3.2.9 on 2021-12-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211207_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='categori',
            name='titletext',
            field=models.TextField(default='some inf', verbose_name='składniki'),
        ),
    ]
