# Generated by Django 3.2.9 on 2021-12-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='temat',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='wiadomosc',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='Imie',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='Nazwisko',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='kod_pocztowy',
        ),
        migrations.DeleteModel(
            name='Kosz',
        ),
    ]
